# Generated by Django 3.1.7 on 2021-06-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flarehive_api', '0003_profile_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flarehive_api.profile'),
        ),
    ]
